### ISSUE TITLE
swap_index can write out bounds and return uninitialized memory

### ISSUE THREAD

**Issue by ammaraskar** [tiby312/reorder#1]
Hi there, we (Rust group @sslab-gatech) are scanning crates on crates.io for potential soundness bugs. We noticed that in `swap_index`, the length returned by the iterator is used to set the length of the vector:

https://github.com/tiby312/reorder/blob/59ad9be6989de8eee948510b850851105ecad22e/src/lib.rs#L46-L56

However, as noted in the documentation for `ExactSizeIterator`'s `len()` function:

> This function has the same safety guarantees as the Iterator::size_hint function.

and then [`size_hint`'s documentation](https://doc.rust-lang.org/std/iter/trait.Iterator.html#method.size_hint) says:

> `size_hint()` is primarily intended to be used for optimizations such as reserving space for the elements of the iterator, but must not be trusted to e.g., omit bounds checks in unsafe code. An incorrect implementation of `size_hint()` should not lead to memory safety violations.

Here's an example of some code that will use uninitialized memory through this method:

```rust
#![forbid(unsafe_code)]

use reorder::swap_index;

struct IteratorWithWrongLength();

impl Iterator for IteratorWithWrongLength {
    type Item = u32;
    fn next(&mut self) -> Option<Self::Item> { None }
}
impl ExactSizeIterator for IteratorWithWrongLength {
    fn len(&self) -> usize { 1024 }
}

fn main() {
    let v = swap_index(IteratorWithWrongLength());

    println!("{:?}", v);
}
```

**Comment by Shnatsel** [comment]
Heads up: this issue has been included in the [RustSec advisory database](https://github.com/RustSec/advisory-db). It will be surfaced by tools such as [cargo-audit](https://github.com/RustSec/cargo-audit) or [cargo-deny](https://github.com/EmbarkStudios/cargo-deny) from now on.

Once a fix is released to crates.io, please open a pull request to update the advisory with the patched version, or file an issue on [the advisory database repository](https://github.com/RustSec/advisory-db).

**Comment by tiby312** [comment]
Thank you for the heads up! I submitted a pull request to fix this problem.

**Comment by tiby312** [comment]
looks like the pull request made it in. thanks for the help
