### ISSUE TITLE
reorder_index contains a lot of potential UB

### ISSUE THREAD

**Issue by changhe3** [tiby312/reorder#2]
Here is a modified version that I tried to get rid of most of the UBs AFAIK:

```rust
use uninit::prelude::*;

pub fn reorder_index<A>(arr: &mut [A], indices: &mut [usize]) {
    assert_eq!(arr.len(), indices.len());

    let arr: &mut [MaybeUninit<_>] = unsafe { arr.manually_drop_mut().as_out().as_mut_uninit() };
    for i in 0..arr.len() {
        while indices[i] != i {
            let old_target_i = indices[indices[i]];

            //let old_target_e = arr[index[i]];
            let mut old_target_e = std::mem::MaybeUninit::<A>::uninit();
            unsafe {
                old_target_e
                    .as_mut_ptr()
                    .write(arr[indices[i]].as_ptr().read());
            }

            // arr[index[i]] = arr[i];
            // Since the object arr[index[i]] is aliased to old_target_e, we cannot produce
            // mutable reference to it nor assign to it.
            unsafe {
                arr[indices[i]].as_mut_ptr().write(arr[i].as_ptr().read());
            }
            // Now that old_target_e is not longer aliased, we can call assume_init
            let old_target_e = unsafe { old_target_e.assume_init() };

            indices[indices[i]] = indices[i];

            indices[i] = old_target_i;

            //arr[i] = old_target_e;
            // arr[i] is aliased to arr[index[i]
            arr[i].as_out().write(old_target_e);
        }
    }
}


```

**Comment by changhe3** [comment]
https://github.com/tiby312/reorder/blob/5a7aa092eaf9de87300e6c5b25a2df953d60ee90/src/lib.rs#L118
`std::mem::MaybeUninit::<A>::zeroed().assume_init()` is instant UB [if zero is not a valid bit pattern for `A`](https://doc.rust-lang.org/std/mem/union.MaybeUninit.html#initialization-invariant).

In general, you cannot create value out of thin air for arbitrary generic type `A`. Only way I can think of is to wrap everything in `&mut MaybeUninit<A>` and use `read` and `write` on the raw pointer.

**Comment by tiby312** [comment]
@changhe3  Thank you for the feedback! After looking at it more i agree there is a lot of UB. Sorry about that. Is there a way to avoid the uninit crate dependency? Only thing stopping me from putting this version in.

**Comment by tiby312** [comment]
cancel that! I just went ahead and added the dependency and made a new crate version. I also yanked the last versions. LMK if any problems

**Comment by changhe3** [comment]
I haven't actually tested with Miri that it's not guaranteed that the code is UB-free. I will open a thread on users.rust-lang.org to ask people to review the code.

**Comment by changhe3** [comment]
> 
> 
> @changhe3 Thank you for the feedback! After looking at it more i agree there is a lot of UB. Sorry about that. Is there a way to avoid the uninit crate dependency? Only thing stopping me from putting this version in.

Sorry about that. `uninit` crate should be trivially avoidable. I used it since my crate already was using it.
```rust
pub fn reorder_index<A>(arr: &mut [A], indices: &mut [usize]) {
    assert_eq!(arr.len(), indices.len());

    let arr = unsafe { &mut *(arr as *mut [A] as *mut [MaybeUninit<A>]) };
    for i in 0..arr.len() {
        while indices[i] != i {
            let old_target_i = indices[indices[i]];

            //let old_target_e = arr[index[i]];
            let mut old_target_e = std::mem::MaybeUninit::<A>::uninit();
            unsafe {
                old_target_e
                    .as_mut_ptr()
                    .write(arr[indices[i]].as_ptr().read());
            }

            // arr[index[i]] = arr[i];
            // Since the object arr[index[i]] is aliased to old_target_e, we cannot produce
            // mutable reference to it nor assign to it.
            unsafe {
                arr[indices[i]].as_mut_ptr().write(arr[i].as_ptr().read());
            }
            // Now that old_target_e is not longer aliased, we can call assume_init
            let old_target_e = unsafe { old_target_e.assume_init() };

            indices[indices[i]] = indices[i];

            indices[i] = old_target_i;

            //arr[i] = old_target_e;
            // arr[i] is aliased to arr[index[i]
            arr[i].as_mut_ptr().write(old_target_e);
        }
    }
}
```

**Comment by changhe3** [comment]
It seems we can do this with entirely safe code /facepalm...
https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=ef486737cb1641c85bd7e7f6ffe9bd94

The full thread is here.
https://users.rust-lang.org/t/reorder-an-array-according-to-given-indexes/58375

**Comment by tiby312** [comment]
Thanks for figuring this out. I just pushed a new version to crates.io with the safe version. I also decided to make the auxiliary array version safe by adding `Clone` and `Default` trait bounds.  It's interesting that you can avoid the trait bounds when not using aux array. Maybe someday I will try to use unsafe properly to remove these bounds (I think you have to use unsafe in this case).
